### ISSUE TITLE
fix: Some notes are empty in the notesFolder

### ISSUE THREAD

**Issue by MuhametSmaili** [MuhametSmaili/note-it#71]
# 📚 Summary 
Some notes inside the notes folder are empty. This happens because the viewer extension is not the same as the editor.
In the viewer note editor, we are not including all the plugins that we are using for the notes editor.

# 📝 TODO 

- [x] Write the same extensions as in the editor
- [x] Limit the size of the note-viewer editor
- [x] Do not allow scrolling
- [x] Images should be shown and resized for the specific size.
